### ISSUE TITLE
emma can not be installed (R 3.3.0)

### ISSUE THREAD

**Issue by xiekunwhy** [Gregor-Mendel-Institute/mlmm#8] opened 2016-09-04 10:44 UTC
Hi,
emma package can not be installed under R 3.3.0, can any one help me?
install.packages("~/opt/pipeline/mlmm/emma_1.1.2.tar.gz")
Installing package into ‘~/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘~/mlmm/emma_1.1.2.tar.gz’ is not available (for R version 3.3.0)

**Comment by visegura** [comment] 2016-09-07 07:23
Hi,
There must be an issue with your installation because I've just managed to install emma from the file "emma_1.1.2.tar.gz" under R 3.3.1. Maybe one problem is that there exists another emma package from CRAN (https://cran.r-project.org/web/packages/emma/index.html) which has the same name but does different things. This may interfere with your installation. Please make sure before installing from emma_1.1.2.tar.gz that no emma package is already installed.
Hope it helps,
Vincent

**Comment by LTibbs** [comment] 2017-10-03 19:03
I am also having a problem installing emma, but with R version 3.4.1. I am working in RStudio.
I downloaded emma_1.1.2.zip from http://mouse.cs.ucla.edu/emma/index.html ,  as instructed in the mlmm README file.

Here is my code:
`install.packages("C:/Users/Downloads/emma_1.1.2.zip", repos = NULL, type = "win.binary")
library(emma)`

And here is the output I get:
`> install.packages("C:/Users/Downloads/emma_1.1.2.zip", repos = NULL, type = "win.binary")`
`Installing package into ‘C:/Users/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)`
`package ‘emma’ successfully unpacked and MD5 sums checked`
`> library(emma)`
`Error: package ‘emma’ was built before R 3.0.0: please re-install it`

I have uninstalled and re-installed emma a couple of times, and checked that no other packages called "emma" are installed as suggested in the previous post. I also tried to update packages (using RStudio's Tools>Check for Package Updates) but it said that "All packages are up to date."

This also means that I am also unable to install the mlmm package; when I try (using `library(devtools); install_github("Gregor-Mendel-Institute/mlmm")`), I get the error `Error : package 'emma' was built before R 3.0.0: please re-install it`. So, it looks like I need to address this emma issue before I can use mlmm.

How can I solve this? Thanks!

**Comment by timeu** [comment] 2017-10-03 19:08
@LTibbs : can you try running `update.packages(checkBuilt = TRUE, ask = FALSE)` after installing the emma_1.1.2.zip package and see if that fixes the issue

**Comment by LTibbs** [comment] 2017-10-03 19:15
@timeu , thanks for that quick response. I just tried that, and it did allow `library(emma)` to run successfully afterwards, but I'm still having problems.

It looks like this command updated the emma package to that available on CRAN rather than the UCLA version needed for mlmm. When I now try to install the mlmm package, it gives a different error, but again says I need a different version of emma.

Here is my code now:
`install.packages("C:/Users/Downloads/emma_1.1.2.zip", repos = NULL, type = "win.binary")
update.packages(checkBuilt = TRUE, ask = FALSE)
library(emma)
library(devtools); install_github("Gregor-Mendel-Institute/mlmm")`

And here is the error message I get now:
`Error : package 'emma' 0.1.0 was found, but >= 1.1.2 is required by 'mlmm'`
`ERROR: lazy loading failed for package 'mlmm'`
`* removing 'C:/Users/Documents/R/win-library/3.4/mlmm'`
`Installation failed: Command failed (1)`

**Comment by timeu** [comment] 2017-10-03 19:20
It seems that you also have this https://cran.r-project.org/web/packages/emma/index.html installed and it is picked up when loading `mlmm`. Can you make sure to uninstall the `emma` package first (`remove.packages('emma')`) and then re-install it.

**Comment by LTibbs** [comment] 2017-10-03 19:26
Yes, as I mentioned, it looks like `update.packages(checkBuilt = TRUE, ask = FALSE)` updates the UCLA emma to the CRAN emma. 
Now, when I uninstall emma and reinstall it (`remove.packages('emma')` followed by `install.packages("C:/Users/Downloads/emma_1.1.2.zip", repos = NULL, type = "win.binary")` I am back exactly where I started in my first post, with the error `Error: package ‘emma’ was built before R 3.0.0: please re-install it`
Thanks for your quick responses, @timeu.

**Comment by timeu** [comment] 2017-10-03 19:33
I don't have Windows but could you try to install it from source instead of win.binary and see if that helps: 

`install.packages("C:/Users/Downloads/emma_1.1.2.zip", repos = NULL, type = "source")`

**Comment by LTibbs** [comment] 2017-10-03 19:50
I did try that, but it didn't seem to help.
Now, my code is:
`install.packages("C:/Users/Downloads/emma_1.1.2.zip", repos = NULL, type = "source")`
`library(emma)`

But I still get the same error:
`Error: package ‘emma’ was built before R 3.0.0: please re-install it`

I'm going to see if I can use a different version of R to get around this, but please let me know if you have other ideas!

**Comment by timeu** [comment] 2017-10-03 20:01
Ok, maybe @visegura  has an idea

**Comment by visegura** [comment] 2017-10-03 20:10
Well this issue is quite annoying... I'm also not on Windows so I do not have myself this issue but I have a virtualbox with windows in which I can reproduce this. 
I suppose one can try to build again the package emma from the source functions available in the zip file. The other option would be to update mlmm to include the required functions from emma, but I would prefer to try the former option first.  I can give it a go in the next few days and let you know.

**Comment by LTibbs** [comment] 2017-10-03 20:17
@visegura, that would be great if you find a way around this.
I did try to run emma on progressively older versions of R, but I have reached the earliest version of R that can be used with RStudio (version 2.11.1), and still got this error:
 `Error: package 'emma' was built before R 2.10.0: please re-install it`
So, for now I may wait on your solution or look into other ways to analyze my data.

**Comment by timeu** [comment] 2017-10-03 20:28
@visegura :+1: 
@LTibbs : what you also can try to do in the meantime as a workaround to run R either as a docker image of R on Windows 10 (https://docs.docker.com/docker-for-windows/install/) or use the Windows Subsystem for Linux to run R inside an Ubuntu bash inside a Windows 10 (https://stackoverflow.com/questions/38818613/how-to-execute-linux-commands-from-r-via-bash-under-the-windows-subsystem-for-li) ;-)

Both workarounds are probably a bit involved, so @visegura solution to re-create the windows binaries for the emma package would be the best solution.

**Comment by visegura** [comment] 2017-10-04 16:02
Hi,
I have just made a new build of emma with the last R version (3.4.2) on Ubuntu 16.04 LTS using the command: R CMD build. I further managed to install emma from the resulting emma.tar.gz in R 3.4.0 on Windows 7 in my virtualbox. Then I could successfully install mlmm.
So please find the emma.tar.gz archive, give it a go and let me know if it works.
Best regards,
[emma_1.1.2.tar.gz](https://github.com/Gregor-Mendel-Institute/mlmm/files/1356516/emma_1.1.2.tar.gz)

Vincent

**Comment by achateigner** [comment] 2017-10-05 06:47
Worked for me on windows 10!

**Comment by timeu** [comment] 2017-10-05 06:51
@visegura: maybe we should update the README and explain that this modified emma_1.1.2.tar.gz should be used (at least by Windows users)

**Comment by visegura** [comment] 2017-10-05 06:55
@timeu: yes I was about to do it!

**Comment by visegura** [comment] 2017-10-05 07:08
@timeu: done! shall we close the issue then?

**Comment by timeu** [comment] 2017-10-05 08:39
Great thanks. Let's wait until @LTibbs responds and then close it

**Comment by LTibbs** [comment] 2017-10-05 18:08
Yes, your new version of emma does work on the example dataset on Windows 10 for me as well. Sorry for the slow response--I was also trying to get it to work with my real dataset before I posted, but I'm still working on that.
Update: I also have it working with real data. Thanks!

**Closed as completed** 2018-01-03 13:34 UTC
Labels: question
